FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL
ARG VITE_TMDB_API_KEY

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_TMDB_API_KEY=$VITE_TMDB_API_KEY

RUN npm run build


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf